version: "3.8"

services:
  user_service:
    build: ./user_service
    volumes:
      - ./user_service:/usr/src/app
    ports:
      - "8001:8000"
    env_file:
      - ./user_service/.env

  notice_service:
    build: ./notice_service
    volumes:
      - ./notice_service:/usr/src/app
    ports:
      - "8002:8000"
    env_file:
      - ./notice_service/.env

  communication_service:
    build: ./communication_service
    volumes:
      - ./communication_service:/usr/src/app
    ports:
      - "8003:8000"
    env_file:
      - ./communication_service/.env

  reporting_service:
    build: ./reporting_service
    volumes:
      - ./reporting_service:/usr/src/app
    ports:
      - "8004:8000"
    env_file:
      - ./reporting_service/.env
