name: Docker CI/CD

on:
  push:
    branches: [master]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push user_service
      - name: Build and push user_service
        uses: docker/build-push-action@v2
        with:
          context: ./user_service
          file: ./user_service/Dockerfile
          push: true
          tags: qodeways/user_service:${{ github.sha }}

      # Build and Push notice_service
      - name: Build and push notice_service
        uses: docker/build-push-action@v2
        with:
          context: ./notice_service
          file: ./notice_service/Dockerfile
          push: true
          tags: qodeways/notice_service:${{ github.sha }}

      # Build and Push communication_service
      - name: Build and push communication_service
        uses: docker/build-push-action@v2
        with:
          context: ./communication_service
          file: ./communication_service/Dockerfile
          push: true
          tags: qodeways/communication_service:${{ github.sha }}

      # Build and Push reporting_service
      - name: Build and push reporting_service
        uses: docker/build-push-action@v2
        with:
          context: ./reporting_service
          file: ./reporting_service/Dockerfile
          push: true
          tags: qodeways/reporting_service:${{ github.sha }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/communication-notice/
            docker-compose pull
            docker-compose up -d
