name: Docker CI/CD

on:
  push:
    branches: [master]
    paths:
      - "user_service/**"
      - "notice_service/**"
      - "communication_service/**"
      - "reporting_service/**"
  pull_request:
    branches: [master]
    paths:
      - "user_service/**"
      - "notice_service/**"
      - "communication_service/**"
      - "reporting_service/**"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          [
            user_service,
            notice_service,
            communication_service,
            reporting_service,
          ]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Check paths changed
      - name: Detect changed paths
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            user_service:
              - 'user_service/**'
            notice_service:
              - 'notice_service/**'
            communication_service:
              - 'communication_service/**'
            reporting_service:
              - 'reporting_service/**'

      - name: Build and push Docker image
        if: steps.filter.outputs[matrix.service] == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: qodeways/${{ matrix.service }}:${{ github.sha }}

      - name: Deploy to AWS
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/communication-notice/
            docker-compose pull
            docker-compose up -d
